services:
  # 主应用配置
  master:             # docker-compose内的容器名
    container_name: master      # 容器名
    restart: always        # 重启策略: 容器退出时总是重启容器
    build: 
      context: ./packages/portal        # 服务指定上下文目录
      dockerfile: Dockerfile    # 相对于context的dockerfile文件路径
    environment:
      NODE_ENV: 'production' 
    ports:
      - '80:80'          # 端口映射，宿主机端口：容器端口
    volumes:
      # 挂载nginx配置
      - ./nginx.conf:/etc/nginx/nginx.conf
  doc:
    container_name: doc
    restart: always
    build: 
      context: ./packages/document
      dockerfile: Dockerfile
    environment:
      NODE_ENV: 'production'
    depends_on:            # 依赖容器名，会在此容器启动之后启动
      - master
