version: '3.0'
services:
  # 主应用配置
  master:             # docker-compose内的容器名
    container_name: master      # 容器名
    restart: always        # 重启策略: 容器退出时总是重启容器
    build: 
      context: ./       # 服务指定上下文目录
      dockerfile: ./packages/portal/Dockerfile    # 相对于context的dockerfile文件路径
    environment:
      NODE_ENV: 'production' 
    ports:
      - '80:80'          # 端口映射，宿主机端口：容器端口
    networks:
        - common-network
  doc:
    container_name: doc
    restart: always
    build: 
      context: ./
      dockerfile: ./packages/document/Dockerfile
    environment:
      NODE_ENV: 'production'
    networks:
      - common-network
    depends_on:            # 依赖容器名，会在此容器启动之后启动
      - master
  chat:
    container_name: chat
    restart: always
    build: 
      context: ./
      dockerfile: ./packages/chat/Dockerfile
    environment:
      NODE_ENV: 'production'
    networks:
      - common-network
    depends_on:            # 依赖容器名，会在此容器启动之后启动
      - master
networks:
  common-network:
    external: true 