version: '1.0'
name: pipeline-doc
displayName: pipeline-doc
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - feat-document
    paths:
      include:
        - packages/document/
stages:
  - name: stage-3661a552
    displayName: 测试
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: ut@nodejs
        name: unit_test_nodejs
        displayName: Nodejs 单元测试
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - '# 在这里输入测试命令'
          - cd ./packages/document
          - npm install && npm run test:unit
        report:
          path: mochawesome-report
          file: mochawesome.json
          index: mochawesome.html
        checkpoints: []
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'